// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Ow4kYIhm-jmlwR07jYKYUkc0lHXcLUk',
    appId: '1:801271750517:web:16012dd3d4445e5c317d3c',
    messagingSenderId: '801271750517',
    projectId: 'project2-97040',
    authDomain: 'project2-97040.firebaseapp.com',
    storageBucket: 'project2-97040.firebasestorage.app',
    measurementId: 'G-P1N8P672N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwsEWvxpdIfTBWvoRiC-IMfS4Olekcgtg',
    appId: '1:801271750517:android:9e3a49bd6e7f4e24317d3c',
    messagingSenderId: '801271750517',
    projectId: 'project2-97040',
    storageBucket: 'project2-97040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHBWh2rZsCOjvtguNj99VkfkAEA2bHUSw',
    appId: '1:801271750517:ios:ef5678b9e11e062d317d3c',
    messagingSenderId: '801271750517',
    projectId: 'project2-97040',
    storageBucket: 'project2-97040.firebasestorage.app',
    iosBundleId: 'com.example.wandermate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHBWh2rZsCOjvtguNj99VkfkAEA2bHUSw',
    appId: '1:801271750517:ios:ef5678b9e11e062d317d3c',
    messagingSenderId: '801271750517',
    projectId: 'project2-97040',
    storageBucket: 'project2-97040.firebasestorage.app',
    iosBundleId: 'com.example.wandermate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Ow4kYIhm-jmlwR07jYKYUkc0lHXcLUk',
    appId: '1:801271750517:web:f7672031234b1141317d3c',
    messagingSenderId: '801271750517',
    projectId: 'project2-97040',
    authDomain: 'project2-97040.firebaseapp.com',
    storageBucket: 'project2-97040.firebasestorage.app',
    measurementId: 'G-SPLBQ07FQ9',
  );
}
